services:
    sfynx.admin.admin.group:
        class: Sfynx\AdminBundle\Admin\GroupAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: gestion_utilisateur, label: group }
        arguments: [null, Sfynx\AuthBundle\Entity\Group, SfynxAdminBundle:GroupAdmin]
                
    sfynx.admin.admin.user:
        class: Sfynx\AdminBundle\Admin\UserAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: gestion_utilisateur, label: user }
        arguments: [null, Sfynx\AuthBundle\Entity\User, SfynxAdminBundle:UserAdmin]
        calls:
          - [ setUserManager, ['@fos_user.user_manager'] ]  
                
    sfynx.admin.admin.role:
        class: Sfynx\AdminBundle\Admin\RoleAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: gestion_utilisateur, label: role }
        arguments: [null, Sfynx\AuthBundle\Entity\Role, SfynxAdminBundle:RoleAdmin]
                
    sfynx.admin.admin.permission:
        class: Sfynx\AdminBundle\Admin\PermissionAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: gestion_utilisateur, label: permission }
        arguments: [null, Sfynx\AuthBundle\Entity\Permission, SfynxAdminBundle:PermissionAdmin]
                
    sfynx.admin.admin.historicalpage:
        class: Sfynx\AdminBundle\Admin\HistoricalPageAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: gestion_cms, label: historical page }
        arguments: [null, Sfynx\CmfBundle\Entity\HistoricalStatus, SfynxAdminBundle:HistoricalPageCMS]